using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class Login : MonoBehaviour
{
    public Button helpBtn;
    public Button googleLoginBtn;
    public Button guestLoginBtn;
    public Text statusTxt;
    
    void Awake(){
        helpBtn.onClick.AddListener(OnHelp);
    }
    

    // Update is called once per frame
    void Update()
    {
        
    }



    void OnHelp(){
        MessageBox.ShowMessage("This game saves your progress in cloud, in order to preserve the data. We need you to login with either Google or Guest login.", "Why Login?");
    }
}
