using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Hole : MonoBehaviour
{
    public void OnTriggerEnter2D(Collider2D other){
        if(other.tag == "Player"){
            Debug.Log(other.name + " Entered hole");

            GameManager.Hole(transform.position);
        }
    }

    public void OnTriggerExit2D(Collider2D other){
        if(other.tag == "Player"){
            Debug.Log(other.name + " Exited hole");

            GameManager.CancelHole();
        }
    }
}
